name: Rust Audit Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo_audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Rust
      run: rustup update stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run cargo-audit
      run: cargo audit

    # Other jobs such as build, test, deploy, etc.
